PIG-2785: NoClassDefFoundError after upgrading to pig 0.10.0 from 0.9.0 (matterhayes via sms)
git-svn-id: https://svn.apache.org/repos/asf/pig/trunk@1375873 13f79535-47bb-0310-9956-ffa450edef68